### ISSUE TITLE
Add health endpoints

### ISSUE THREAD

**Issue by romanrguez192** [Azordev/backend-template#13]
### Explanation

We need endpoints to check the health of the server and database. They would look something like this:

```
GET /health-server => boolean and some info
GET /health-db => boolean and some info
```

### Checklist

 This issue can be closed when the following tasks are completed:
 
 - [ ] Test `npm test` have passed. ✔
 - [ ] The health-server endpoint works properly.
 - [ ] The health-db endpoint works properly.

**Comment by Israel-Laguan** [comment]
Please verify, this should be partially done

I added

`GET /ping` open check if server is working
`GET /status` Needs JWT and check details on the server
