### ISSUE TITLE
Set up a way of handling environments

### ISSUE THREAD

**Issue by romanrguez192** [Azordev/backend-template#15]
### Explanation

In projects we usually manage at least three different environments: development, test and production. We need a way of properly handling the configuration files for each one of them.

### Checklist

 This issue can be closed when the following tasks are complete:
 
 - [ ] Test `npm test` have passed .✔
 - [ ] We can easily set up the development environment.
 - [ ] We can easily set up the testing environment.
 - [ ] We can easily set up the production environment.
 - [ ] It's easy to add environment variables.

**Comment by Israel-Laguan** [comment]
Please verify, this should be done

I added support for

- LOCAL to test with local data, like installing on you PC the database
- TEST and ENV to develop and check locally but using docker
- QA and STAGING to develop in a production-like database
- PRODUCTION to work directly on the production database

Please check this code:
https://github.com/Azordev/backend-template/blob/ebc38aa0ac7c7c7d220042603796fb8bce832a95/src/server/environments/environment.ts#L44-L64
