### ISSUE TITLE
Add project configuration based on coolticket-server

### ISSUE THREAD

**Issue by romanrguez192** [Azordev/backend-template#17]
### Explanation

The coolticket-server has some interesting configurations. We could take some of those and use them in this template.

### Checklist

 This issue can be closed when the following tasks are complete:
 
 - [ ] Test `npm test` have passed .✔
 
### References

[Coolticket Server](https://github.com/Israel-Laguan/coolticket-server)

**Comment by Israel-Laguan** [comment]
I advanced on this one, but would need more validation
