### ISSUE TITLE
Add a way to log errors at backend

### ISSUE THREAD

**Issue by Katsu08** [Azordev/backend-template#7]
### Explanation
 When some error occurs in the production stage it is necesary that the frontend can send this error information to the backend, so it can save it on a database table or file like `errors.log`.

### Checklist
 Describe the key points to complete the task. This points will help in the pull request test.

 This issue can be closed when the following tasks are completed:
 
 - [ ] There is a way to handle errors (Frontend can send u errors and u are saving this errors on some place that we can check last).

**Comment by Israel-Laguan** [comment]
Please verify, this should be done
