### ISSUE TITLE
Add linters and formatters

### ISSUE THREAD

**Issue by romanrguez192** [Azordev/backend-template#9]
### Explanation

It would be beneficial if the project had linters and formatters in order to improve the quality of the code. I'd suggest using ESLint combined with Prettier, with their respective config files and VSCode settings. In addition, we could set up a git pre-commit hook with it.

### Checklist

 This issue can be closed when the following tasks are completed:
 
 - [ ] Test `npm test` have passed. ✔
 - [ ] The project includes a linter.
 - [ ] The project includes a code formatter.
 - [ ] The project has their config files.
 - [ ] The project has VSCode settings.
 - [ ] The project has a pre-commit hook.

**Comment by Israel-Laguan** [comment]
We would need to check if current rules are good to go
